//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportTamilRecipesIntoRealmDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class samayal365_chutney_recipe_categories
    {
        public int id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int count { get; set; }
        public string name { get; set; }
        public string image_path { get; set; }
    }
}
