//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportTamilRecipesIntoRealmDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class samayal365_tiffin_recipes
    {
        public int id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int category_id { get; set; }
        public string name { get; set; }
        public string recipe_detail { get; set; }
        public string image_path { get; set; }
        public bool is_favorite { get; set; }
        public int ratings { get; set; }
        public int rating1_count { get; set; }
        public int rating2_count { get; set; }
        public int rating3_count { get; set; }
        public int rating4_count { get; set; }
        public int rating5_count { get; set; }
        public Nullable<System.DateTime> rating_updated_at { get; set; }
        public int rating_total { get; set; }
        public Nullable<int> recipe_detail_checksum { get; set; }
        public bool can_publish { get; set; }
    
        public virtual samayal365_tiffin_recipe_categories samayal365_tiffin_recipe_categories { get; set; }
    }
}
