//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportTamilRecipesIntoRealmDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TamilRecipeEntities : DbContext
    {
        public TamilRecipeEntities()
            : base("name=TamilRecipeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<samayal365_briyani_recipe_categories> samayal365_briyani_recipe_categories { get; set; }
        public virtual DbSet<samayal365_briyani_recipes> samayal365_briyani_recipes { get; set; }
        public virtual DbSet<samayal365_chettinadu_recipes> samayal365_chettinadu_recipes { get; set; }
        public virtual DbSet<samayal365_chutney_recipe_categories> samayal365_chutney_recipe_categories { get; set; }
        public virtual DbSet<samayal365_tiffin_recipe_categories> samayal365_tiffin_recipe_categories { get; set; }
        public virtual DbSet<samayal365_tiffin_recipes> samayal365_tiffin_recipes { get; set; }
    }
}
