//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeToSqlImporter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecipeModelContext : DbContext
    {
        public RecipeModelContext()
            : base("name=RecipeModelContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<samayal365_rice_recipe_categories> samayal365_rice_recipe_categories { get; set; }
        public DbSet<samayal365_rice_recipes> samayal365_rice_recipes { get; set; }
    }
}
