//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeToSqlImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe
    {
        public int id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int category_id { get; set; }
        public string name { get; set; }
        public string image_path { get; set; }
        public string recipe_detail { get; set; }
        public bool is_favorite { get; set; }
        public int ratings { get; set; }
    
        public virtual recipe_categories recipe_categories { get; set; }
    }
}
