//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeToSqlImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe_categories
    {
        public recipe_categories()
        {
            this.recipes = new HashSet<recipe>();
        }
    
        public int id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int count { get; set; }
        public string name { get; set; }
        public string image_path { get; set; }
    
        public virtual ICollection<recipe> recipes { get; set; }
    }
}
